### ISSUE TITLE
[Not an issue but...] Why this won't work with the EUR version?

### ISSUE THREAD

**Issue by danylopez123** [rhmodding/RHMPatch#1]
I mean, i never used this tool and i saw it's only compatible with the US version, but i dont know what is different between the European and US version of the game, what is different?

Also, another question, if i owned the US version, does this work only with the cartridge or does it also work with the one you download from the eShop?

**Comment by DPS2004** [comment]
first off there is no US cartridge version, and if there were it would work. I think the location of certain files are different in the eu version so that is why it does not work.
